### ISSUE TITLE
The speed of the MotorRectangle is very small

### ISSUE THREAD

**Issue by slakibk** [tessarakkt/godot4-oceanfft#15]
Thanks for the work. I have a question about the speed of the MotorRectangle. How can I increase its speed? Changing thrust_power_main does not help. Using Godot v4.2.2.rc1.official [c7fb0645a]

**Comment by Tattomoosa** [comment]
Increasing `thrust_power_main` does work. The propeller location must be underwater and the value needed might be higher than you'd expect, not really sure why that is.

**Comment by slakibk** [comment]
You're right. I had to set the value to 1000000.0 to start moving at normal speed. This may be due to the force applied in BuoyancyBody3D. 
Thanks for the quick response.
