### ISSUE TITLE
Key bindings does not work

### ISSUE THREAD

**Issue by maliyshock** [tessarakkt/godot4-oceanfft#7]
I do not know how to describe it properly, but on my sistem keys presented in readme file not working.

**Comment by maliyshock** [comment]
I made it work by changing `var motion_enabled ` to `true`

And removed the row with this condition `if motion_enabled and current:`

**Comment by tessarakkt** [comment]
That sounds like you were initially trying to use the keybindings in menu mode, when the key bindings and mouse motion are intentionally disabled.

Does it work without modification if you switch from menu mode to free cam mode by pressing the ` key? I notice your profile says you are in Germany, so if using a QWERTZ keyboard, this appears to be Shift and the key to the left of backspace. If this doesn't switch the mode (the UI will also disappear when the switch happens), you may need to change the key binding in the project settings for toggle_ocean_debug to something more QWERTZ friendly.

The readme indicates this keybinding is `/~, but I am realizing now that combination only applies to QWERTY keyboards (and maybe a few others).

**Comment by maliyshock** [comment]
yes, you are right. I am in germany, but i am not german and i am using ENG (british) keyboard.
I just did not realised that i had to toggle the mode to be able to use free camera.
Thank you for the help!

By the way
